//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.16 at 09:33:32 AM CDT 
//


package edu.uiowa.medline.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Journal"/>
 *         &lt;element ref="{}ArticleTitle"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{}Pagination"/>
 *             &lt;element ref="{}ELocationID" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element ref="{}ELocationID" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *         &lt;element ref="{}Abstract" minOccurs="0"/>
 *         &lt;element ref="{}Affiliation" minOccurs="0"/>
 *         &lt;element ref="{}AuthorList" minOccurs="0"/>
 *         &lt;element ref="{}Language" maxOccurs="unbounded"/>
 *         &lt;element ref="{}DataBankList" minOccurs="0"/>
 *         &lt;element ref="{}GrantList" minOccurs="0"/>
 *         &lt;element ref="{}PublicationTypeList"/>
 *         &lt;element ref="{}VernacularTitle" minOccurs="0"/>
 *         &lt;element ref="{}ArticleDate" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="PubModel" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="Print"/>
 *             &lt;enumeration value="Print-Electronic"/>
 *             &lt;enumeration value="Electronic"/>
 *             &lt;enumeration value="Electronic-Print"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Article")
public class Article {

    @XmlElementRefs({
        @XmlElementRef(name = "AuthorList", type = AuthorList.class),
        @XmlElementRef(name = "DataBankList", type = DataBankList.class),
        @XmlElementRef(name = "GrantList", type = GrantList.class),
        @XmlElementRef(name = "ArticleDate", type = ArticleDate.class),
        @XmlElementRef(name = "Pagination", type = Pagination.class),
        @XmlElementRef(name = "ELocationID", type = ELocationID.class),
        @XmlElementRef(name = "Affiliation", type = Affiliation.class),
        @XmlElementRef(name = "VernacularTitle", type = VernacularTitle.class),
        @XmlElementRef(name = "PublicationTypeList", type = PublicationTypeList.class),
        @XmlElementRef(name = "Abstract", type = Abstract.class),
        @XmlElementRef(name = "Language", type = Language.class),
        @XmlElementRef(name = "Journal", type = Journal.class),
        @XmlElementRef(name = "ArticleTitle", type = ArticleTitle.class)
    })
    protected List<Object> content;
    @XmlAttribute(name = "PubModel", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String pubModel;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "ELocationID" is used by two different parts of a schema. See: 
     * line 65 of file:/Users/schappetj/Documents/workspace/DemoMavenSpring/src/main/xsd/nlmmedlinecitationset_120101.xsd
     * line 63 of file:/Users/schappetj/Documents/workspace/DemoMavenSpring/src/main/xsd/nlmmedlinecitationset_120101.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthorList }
     * {@link DataBankList }
     * {@link GrantList }
     * {@link ArticleDate }
     * {@link Pagination }
     * {@link ELocationID }
     * {@link Affiliation }
     * {@link VernacularTitle }
     * {@link PublicationTypeList }
     * {@link Abstract }
     * {@link Language }
     * {@link Journal }
     * {@link ArticleTitle }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the pubModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubModel() {
        return pubModel;
    }

    /**
     * Sets the value of the pubModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubModel(String value) {
        this.pubModel = value;
    }

}
