//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.16 at 09:33:32 AM CDT 
//


package edu.uiowa.medline.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}RefSource"/>
 *         &lt;element ref="{}PMID" minOccurs="0"/>
 *         &lt;element ref="{}Note" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RefType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="CommentOn"/>
 *             &lt;enumeration value="CommentIn"/>
 *             &lt;enumeration value="ErratumIn"/>
 *             &lt;enumeration value="ErratumFor"/>
 *             &lt;enumeration value="PartialRetractionIn"/>
 *             &lt;enumeration value="PartialRetractionOf"/>
 *             &lt;enumeration value="RepublishedFrom"/>
 *             &lt;enumeration value="RepublishedIn"/>
 *             &lt;enumeration value="RetractionOf"/>
 *             &lt;enumeration value="RetractionIn"/>
 *             &lt;enumeration value="UpdateIn"/>
 *             &lt;enumeration value="UpdateOf"/>
 *             &lt;enumeration value="SummaryForPatientsIn"/>
 *             &lt;enumeration value="OriginalReportIn"/>
 *             &lt;enumeration value="ReprintOf"/>
 *             &lt;enumeration value="ReprintIn"/>
 *             &lt;enumeration value="Cites"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "refSource",
    "pmid",
    "note"
})
@XmlRootElement(name = "CommentsCorrections")
public class CommentsCorrections {

    @XmlElement(name = "RefSource", required = true)
    protected RefSource refSource;
    @XmlElement(name = "PMID")
    protected PMID pmid;
    @XmlElement(name = "Note")
    protected Note note;
    @XmlAttribute(name = "RefType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refType;

    /**
     * Gets the value of the refSource property.
     * 
     * @return
     *     possible object is
     *     {@link RefSource }
     *     
     */
    public RefSource getRefSource() {
        return refSource;
    }

    /**
     * Sets the value of the refSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefSource }
     *     
     */
    public void setRefSource(RefSource value) {
        this.refSource = value;
    }

    /**
     * Gets the value of the pmid property.
     * 
     * @return
     *     possible object is
     *     {@link PMID }
     *     
     */
    public PMID getPMID() {
        return pmid;
    }

    /**
     * Sets the value of the pmid property.
     * 
     * @param value
     *     allowed object is
     *     {@link PMID }
     *     
     */
    public void setPMID(PMID value) {
        this.pmid = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link Note }
     *     
     */
    public Note getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link Note }
     *     
     */
    public void setNote(Note value) {
        this.note = value;
    }

    /**
     * Gets the value of the refType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefType() {
        return refType;
    }

    /**
     * Sets the value of the refType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefType(String value) {
        this.refType = value;
    }

}
