//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.16 at 09:33:32 AM CDT 
//


package edu.uiowa.medline.xml;

import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{}Year"/>
 *           &lt;choice>
 *             &lt;sequence>
 *               &lt;element ref="{}Month"/>
 *               &lt;element ref="{}Day" minOccurs="0"/>
 *             &lt;/sequence>
 *             &lt;element ref="{}Season"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *         &lt;element ref="{}MedlineDate"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "year",
    "month",
    "day",
    "season",
    "medlineDate"
})
@XmlRootElement(name = "PubDate")
public class PubDate {

    @XmlElement(name = "Year")
    protected Year year;
    @XmlElement(name = "Month")
    protected Month month;
    @XmlElement(name = "Day")
    protected Day day;
    @XmlElement(name = "Season")
    protected Season season;
    @XmlElement(name = "MedlineDate")
    protected MedlineDate medlineDate;

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link Year }
     *     
     */
    public Year getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link Year }
     *     
     */
    public void setYear(Year value) {
        this.year = value;
    }

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link Month }
     *     
     */
    public Month getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link Month }
     *     
     */
    public void setMonth(Month value) {
        this.month = value;
    }

    /**
     * Gets the value of the day property.
     * 
     * @return
     *     possible object is
     *     {@link Day }
     *     
     */
    public Day getDay() {
        return day;
    }

    /**
     * Sets the value of the day property.
     * 
     * @param value
     *     allowed object is
     *     {@link Day }
     *     
     */
    public void setDay(Day value) {
        this.day = value;
    }

    /**
     * Gets the value of the season property.
     * 
     * @return
     *     possible object is
     *     {@link Season }
     *     
     */
    public Season getSeason() {
        return season;
    }

    /**
     * Sets the value of the season property.
     * 
     * @param value
     *     allowed object is
     *     {@link Season }
     *     
     */
    public void setSeason(Season value) {
        this.season = value;
    }

    /**
     * Gets the value of the medlineDate property.
     * 
     * @return
     *     possible object is
     *     {@link MedlineDate }
     *     
     */
    public MedlineDate getMedlineDate() {
        return medlineDate;
    }

    /**
     * Sets the value of the medlineDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedlineDate }
     *     
     */
    public void setMedlineDate(MedlineDate value) {
        this.medlineDate = value;
    }
    
    public Date getDate() {
    	Calendar cal = Calendar.getInstance();
    	int month = 0;
    	int day = 1;
    	int year;
    	
    	try {
    		
    		if(getYear() != null) {
    			year = Integer.parseInt(getYear().getContent());
    		} else {
    			return null;
    		}
    	}catch (NumberFormatException e) {
    		return null;
    	}catch (NullPointerException e) {
    		return null;
    	}
    	try {
    		month = Integer.parseInt(getMonth().getContent())-1;
		} catch (NullPointerException e) {
			month = 0;
		} catch (NumberFormatException e) {
		
			HashMap<String, Integer> months = new HashMap<String,Integer>();
			months.put("jan", 0);
			months.put("feb", 1);
			months.put("mar", 2);
			months.put("apr", 3);
			months.put("may", 4);
			months.put("jun", 5);
			months.put("jul", 6);
			months.put("aug", 7);
			months.put("sep", 8);
			months.put("oct", 9);
			months.put("nov", 10);
			months.put("dec", 11);
			month = months.get(getMonth().getContent().toLowerCase());
		}
    	if (getDay() != null) {
			day = Integer.parseInt(getDay().getContent());
		}
    	cal.set(year,month,day);
    	return cal.getTime();
    }

}
